[plugin]
name = "bilibili_video_sender_plugin"
version = "1.0.7"
enabled = true

# MaiBot events_manager 版本兼容性配置
# true: 新版本events_manager（0.10.2及以上），返回5元组
# false: 旧版本events_manager（0.10.2以下），返回3元组
use_new_events_manager = true

[bilibili]

#从这里开始
use_wbi = true
prefer_dash = true
fnval = 4048
fourk = false
qn = 0
platform = "pc"
high_quality = false
try_look = false
#到这里结束的配置不要改

# 账号 Cookie：更高画质/大会员鉴权必需
# 可选：用于生成 session 的 buvid3（浏览器 Cookie 中可获得）

# 视频发送相关配置
enable_video_splitting = true
delete_original_after_split = true
# 视频文件大小限制（MB），不要改
max_video_size_mb = 100
# 是否启用视频压缩功能
enable_video_compression = true
# 压缩质量 (1-51，数值越小质量越高，推荐18-28)
compression_quality = 28

[ffmpeg]
# FFmpeg相关配置
show_warnings = true

# 硬件加速配置
# 是否启用硬件加速自动检测（推荐开启）
# 启用后将自动检测并使用最佳的硬件编码器，大幅提升视频压缩速度
enable_hardware_acceleration = true

# 强制使用特定编码器（留空则自动选择最佳编码器）
# 可选值：
#   libx264 - CPU软件编码（兼容性最好，速度最慢）
#   h264_nvenc - NVIDIA GPU硬件编码（速度最快，需NVIDIA显卡）
#   h264_qsv - Intel Quick Sync Video硬件编码（需Intel CPU支持）
#   h264_amf - AMD GPU硬件编码（需AMD显卡）
#   h264_videotoolbox - Apple硬件编码（仅macOS）
force_encoder = ""

# 编码器优先级（当检测到多个硬件编码器时的选择顺序）
# 插件会按此顺序选择第一个可用的硬件编码器
# nvidia: NVIDIA GPU编码器 (通常速度最快)
# intel: Intel Quick Sync Video (CPU集显，功耗低)
# amd: AMD GPU编码器 (AMD显卡支持)
# apple: Apple VideoToolbox (仅macOS系统)
encoder_priority = ["nvidia", "intel", "amd", "apple"]

[wsl]
# WSL路径转换配置（如果你不知道这是什么，请设为false）
enable_path_conversion = true

[api]
# Napcat http服务器（正向）端口
port = 5700

